/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package equipwise;

//IMPORTS
import ADTs.ItemList;
import ADTs.ItemNode;


/**
 *
 * @author ImaanAhmed
 */
public class BrowseUI extends javax.swing.JPanel {

    /**
     * Creates new form BrowseUI
     */
    
    //DECLARING VARIABLES FOR UI
    private MainFrame mainFrame;    //For main interface
    private ItemList itemList;      //for items list
    
    //CONSTRUCTOR (auto-generated)
    public BrowseUI(MainFrame mainFrame, ItemList itemList) {
        initComponents();
        this.mainFrame = mainFrame;     //Initializing... giving BrowseUI access to MainFrame
        this.itemList = itemList;     //Initializing items on browseUI
        
        loadItems();    //calling method for adding cards to browseUI (populating items)
        
    }
    
    
    //ADDING ITEM CARDS TO UI
    public void loadItems() {
        
        itemsPanel.removeAll();     //clearing panel first
        
        ItemNode current = itemList.getHead();
        
        while(current != null) {
            
            Item item = (Item) current.getData();
            
            itemsPanel.add(new ItemCard(item, mainFrame));
            
            current = current.getNext();
            
        }
        
        itemsPanel.revalidate();
        itemsPanel.repaint();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemsPanel = new javax.swing.JPanel();
        btnAddItem = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(0, 0));

        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        jScrollPane1.setViewportView(itemsPanel);

        btnAddItem.setText("ADD ITEM");
        btnAddItem.addActionListener(this::btnAddItemActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnAddItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    //SEARCHING FOR ITEMS
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
        String keyword = txtSearch.getText().toLowerCase();     //taking in user info
        itemsPanel.removeAll();   //clearing cureent items from screen
        
        ItemNode current = itemList.getHead();
        //
        while(current != null) {
            Item item = (Item) current.getData();
            //
            if(item.getName().toLowerCase().contains(keyword)) {
                ItemCard card = new ItemCard(item, mainFrame);
                itemsPanel.add(card);
            } //end if statement
            
            current = current.getNext();
        } //end while loop
        
        itemsPanel.revalidate();
        itemsPanel.repaint();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        mainFrame.showAddUpdate();
    }//GEN-LAST:event_btnAddItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel itemsPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
