/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package equipwise;

//IMPORTS
import java.awt.Image;  //Import for item image
import static java.awt.Image.SCALE_SMOOTH;  //Import for item size
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;   //Import for item image
import java.net.URL;    //Import for item image url
import java.io.IOException;     //Import for item image
import javax.imageio.ImageIO;
import javax.swing.Icon;


/**
 *
 * @author ImaanAhmed
 */
public class ItemCard extends javax.swing.JPanel {

    /**
     * Creates new form ItemCard
     */
    
    //DECLARING VARIABLES FOR UI
    private Item item;
    private MainFrame mainFrame;
    
    //CONSTRUCTOR (auto-generated)
    public ItemCard(Item item, MainFrame mainFrame) {
        initComponents();
        //Making ItemCard trigger navigation
        this.item = item;
        this.mainFrame = mainFrame;
        
        lblName.setText(item.getName());
        lblPrice.setText("€" + item.getPrice());
        try {
            URL url = new URL(item.getImageURL());
            BufferedImage bufferedImage = ImageIO.read(url);
            //IMAGE SIZE
            Image img = bufferedImage.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
            lblImage.setIcon(new ImageIcon(img));
            lblImage.setText("");
        } catch(Exception e) {
            lblImage.setText("No Image");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImage = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblCondition = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();

        lblImage.setText("image");
        lblImage.setPreferredSize(new java.awt.Dimension(100, 100));

        lblName.setText("Name");

        lblPrice.setText("Price");

        lblCondition.setText("Condition");

        btnView.setText("VIEW");
        btnView.addActionListener(this::btnViewActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCondition)
                    .addComponent(lblPrice)
                    .addComponent(lblName)
                    .addComponent(btnView))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName)
                .addGap(18, 18, 18)
                .addComponent(lblPrice)
                .addGap(18, 18, 18)
                .addComponent(lblCondition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnView)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    //VIEWING PRODUCT
    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        
        mainFrame.showPurchase(item);   //opening purchaseUI for viewing item individually
        
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnView;
    private javax.swing.JLabel lblCondition;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    // End of variables declaration//GEN-END:variables
}
