/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package equipwise;

//IMPORTS
import java.awt.Image;  //Import for item image
import static java.awt.Image.SCALE_SMOOTH;  //Import for item size
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;   //Import for item image
import java.net.URL;    //Import for item image url
import java.io.IOException;     //Import for item image
import javax.imageio.ImageIO;
import javax.swing.Icon;


/**
 *
 * @author ImaanAhmed
 */
public class ItemCard extends javax.swing.JPanel {

    /**
     * Creates new form ItemCard
     */
    
    //DECLARING VARIABLES FOR UI
    private Item item;
    private MainFrame mainFrame;
    
    //CONSTRUCTOR (auto-generated)
    public ItemCard(Item item, MainFrame mainFrame) {
        initComponents();
        //Making ItemCard trigger navigation
        this.item = item;
        this.mainFrame = mainFrame;
        //Setting item image
        lblName.setText(item.getName());
        lblPrice.setText("€" + item.getPrice());
        try {
            URL url = new URL(item.getImageURL());
            BufferedImage bufferedImage = ImageIO.read(url);
            //IMAGE SIZE
            Image img = bufferedImage.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
            lblImage.setIcon(new ImageIcon(img));
            lblImage.setText("");
        } catch(Exception e) {
            lblImage.setText("No Image");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImage = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblCondition = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 2));
        setForeground(new java.awt.Color(0, 0, 153));
        setToolTipText("Item");
        setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        lblImage.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblImage.setForeground(new java.awt.Color(0, 0, 153));
        lblImage.setText("image");
        lblImage.setToolTipText("Item image");
        lblImage.setPreferredSize(new java.awt.Dimension(100, 100));

        lblName.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 0, 153));
        lblName.setText("Name");
        lblName.setToolTipText("Item name");

        lblPrice.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(0, 0, 153));
        lblPrice.setText("Price");
        lblPrice.setToolTipText("Item price");

        lblCondition.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblCondition.setForeground(new java.awt.Color(0, 0, 153));
        lblCondition.setText("Condition");
        lblCondition.setToolTipText("Condition of item");

        btnView.setBackground(new java.awt.Color(255, 255, 204));
        btnView.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnView.setForeground(new java.awt.Color(0, 0, 153));
        btnView.setText("VIEW");
        btnView.setToolTipText("Want to view this item?");
        btnView.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 102), 2, true));
        btnView.addActionListener(this::btnViewActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCondition)
                    .addComponent(lblPrice)
                    .addComponent(lblName)
                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName)
                .addGap(18, 18, 18)
                .addComponent(lblPrice)
                .addGap(18, 18, 18)
                .addComponent(lblCondition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    //VIEWING PRODUCT
    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        
        mainFrame.showPurchase(item);   //opening purchaseUI for viewing item individually
        
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnView;
    private javax.swing.JLabel lblCondition;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    // End of variables declaration//GEN-END:variables
}
