/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package equipwise;

//IMPORTS
import java.awt.CardLayout;
import equipwise.BrowseUI;
import equipwise.PurchaseUI;


/**
 *
 * @author ImaanAhmed
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    
    //DECLARING VARIABLES FOR UI
    private BrowseUI browseUI;
    private PurchaseUI purchaseUI;
    
    //CONSTRUCTOR (auto-generated)
    CardLayout layout;
    public MainFrame() {
        initComponents();
        
        layout = (CardLayout) mainPanel.getLayout();
        
        //CONNECTING CARD LAYOUT
        browseUI = new BrowseUI(this);  //creating panels
        purchaseUI = new PurchaseUI(this);  //creating panels
        
        //ADDING TO CARD LAYOUT
        mainPanel.add(browseUI, "browse");
        mainPanel.add(purchaseUI, "purchase");
        
        //DEFAULT SCREEN
        layout.show(mainPanel, "browse");
    }
    
    
    //Methods to switch between panels
    public void showBrowse() {
        ((CardLayout) mainPanel.getLayout()).show(mainPanel, "browse");
    }
    public void showPurchase(Item item) {
        purchaseUI.setItem(item);
        ((CardLayout) mainPanel.getLayout()).show(mainPanel, "purchase");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new java.awt.CardLayout());

        mainPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        mainPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(mainPanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
