/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package equipwise;

/**
 *
 * @author ImaanAhmed
 */
public class PurchaseUI extends javax.swing.JPanel {

    /**
     * Creates new form PurchaseUI
     */
    
    //DECLARING VARIABLES FOR UI
    private MainFrame mainFrame;    //For main interface
    private Item currentItem;   //For viewing item cards
    
    //CONSTRUCTOR (auto-generated)
    public PurchaseUI(MainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;     //Initializing... giving PurchaseUI access to MainFrame
    }
    
    //METHOS TO VIEW ITEMS
    public void setItem(Item item) {
        
        currentItem = item;
        
        lblName.setText(item.getName());
        lblPrice.setText("€" + item.getPrice());
        lblCondition.setText(item.getCondition());
        lblSeller.setText(item.getSeller());
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImage = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblCondition = new javax.swing.JLabel();
        lblSeller = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnOrder = new javax.swing.JToggleButton();

        setPreferredSize(new java.awt.Dimension(0, 0));

        lblImage.setText("image");

        lblName.setText("Name");

        lblPrice.setText("Price");

        lblCondition.setText("Condition");

        lblSeller.setText("Seller");

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        btnOrder.setText("Place Order");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSeller)
                            .addComponent(lblCondition)
                            .addComponent(lblPrice)
                            .addComponent(lblImage)
                            .addComponent(lblName)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnOrder))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnBack)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnBack)
                .addGap(106, 106, 106)
                .addComponent(lblImage)
                .addGap(116, 116, 116)
                .addComponent(lblName)
                .addGap(18, 18, 18)
                .addComponent(lblPrice)
                .addGap(18, 18, 18)
                .addComponent(lblCondition)
                .addGap(18, 18, 18)
                .addComponent(lblSeller)
                .addGap(18, 18, 18)
                .addComponent(btnOrder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    //RETURNING BACK TO BROWSEUI
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
        mainFrame.showBrowse(); //returning to browseUI
        
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JToggleButton btnOrder;
    private javax.swing.JLabel lblCondition;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblSeller;
    // End of variables declaration//GEN-END:variables
}
