/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package equipwise;

//IMPORTS
import ADTs.ItemList;   //Used to delete items
import javax.swing.JOptionPane;     //Used for messages to user
import ADTs.OrderQueue; //Used to place order (max % items per order)
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.FileWriter;  //Used to generate receipt
import java.io.IOException; //Used for error handling
import java.net.URL;    //for item image
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;   //for item image

/**
 *
 * @author ImaanAhmed
 */

public class PurchaseUI extends javax.swing.JPanel {

    /**
     * Creates new form PurchaseUI
     */
    
    //DECLARING VARIABLES FOR UI
    private MainFrame mainFrame;    //For main interface
    private Item currentItem;   //For viewing item cards
    private OrderQueue orderQueue;  //For adding orders
    private boolean confirmed = false;  //For buying items / printing receipt
    private ItemList itemList;  //For deleting items upon order
    //Variables for receipt:
    private int receiptCount = 0;   //
    private int fileNumber = 1;     //
    private final int MAX_RECEIPTS = 5;     //
    
    
    //CONSTRUCTOR (auto-generated)
    public PurchaseUI(MainFrame mainFrame, OrderQueue orderQueue, ItemList itemList) {
        initComponents();
        this.mainFrame = mainFrame;     //Initializing... giving PurchaseUI access to MainFrame
        this.orderQueue = orderQueue;   //Initializing Q... giving PurchaseUI access to OrderQ
        this.itemList = itemList;   //Initializing SLL... giving PurchaseUI access to items list
    }
    
    //METHOS TO VIEW ITEMS
    public void setItem(Item item) {
        
        currentItem = item;
        
        lblName.setText(item.getName());
        lblPrice.setText("€" + item.getPrice());
        lblCondition.setText(item.getCondition());
        lblSeller.setText(item.getSeller());
        
        //Displaying imageURL
        try {
            URL url = new URL(item.getImageURL());
            BufferedImage bufferedImage = ImageIO.read(url);
            //IMAGE SIZE
            Image img = bufferedImage.getScaledInstance(150, 150, Image.SCALE_SMOOTH);
            
            lblImage.setIcon(new ImageIcon(img));
            lblImage.setText("");
        } catch(Exception e) {
            lblImage.setText("No Image");
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImage = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblCondition = new javax.swing.JLabel();
        lblSeller = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnOrder = new javax.swing.JToggleButton();

        setPreferredSize(new java.awt.Dimension(0, 0));

        lblImage.setText("image");

        lblName.setText("Name");

        lblPrice.setText("Price");

        lblCondition.setText("Condition");

        lblSeller.setText("Seller");

        btnBack.setText("BACK");
        btnBack.addActionListener(this::btnBackActionPerformed);

        btnOrder.setText("Place Order");
        btnOrder.addActionListener(this::btnOrderActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSeller)
                                    .addComponent(lblCondition)
                                    .addComponent(lblPrice)
                                    .addComponent(lblName)))
                            .addComponent(btnOrder)
                            .addComponent(lblImage))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(lblImage)
                .addGap(74, 74, 74)
                .addComponent(lblName)
                .addGap(18, 18, 18)
                .addComponent(lblPrice)
                .addGap(18, 18, 18)
                .addComponent(lblCondition)
                .addGap(18, 18, 18)
                .addComponent(lblSeller)
                .addGap(18, 18, 18)
                .addComponent(btnOrder)
                .addGap(70, 70, 70))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    //RETURNING BACK TO BROWSEUI
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
        mainFrame.showBrowse(); //returning to browseUI
        
    }//GEN-LAST:event_btnBackActionPerformed

    //PLACING ORDER & BUYING ITEM / PRINTING RECEIPT
    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        
        if(!confirmed) {
            orderQueue.enQ(currentItem);
            
            JOptionPane.showMessageDialog(this, "Order placed, please confirm purchase!");
            
            btnOrder.setText("Confirm Purchase?");
            confirmed = true;
            
        } else {
        
            String fileName = generateReceipt(currentItem);
            //Deleting item after purchase
            itemList.delete(currentItem.getId());   //removing item

            JOptionPane.showMessageDialog(this, "Recept saved to " + fileName + "!\nThankyou for using EquipWise :)");
            //generateReceipt(currentItem);
            confirmed = false;
            btnOrder.setText("Place Order?");
            
            mainFrame.refreshBrowse();  //reloading UI
            mainFrame.showBrowse();     //displaying UI
        
        }
        
    }//GEN-LAST:event_btnOrderActionPerformed

    
    //METHOD TO GENERATE RECEIPT TO TXT
        private String generateReceipt(Item item) {
        
            String fileName = "";
            
            try {
                //Creating a new file after every five items purchased:
                if(receiptCount == MAX_RECEIPTS) {
                    fileNumber ++;
                    receiptCount = 0;
                } //end if statement
                
                fileName = "receipt" + fileNumber + ".txt";
                
                FileWriter writer = new FileWriter(fileName, true);
                
                writer.write("\n");
                writer.write("\n-------------------------------------");
                writer.write("\n====== EquipWise  Receipt ======");
                writer.write("\n-------------------------------------");
                writer.write("\nItem:           " + item.getName());
                writer.write("\nPrice:          €" + item.getPrice());
                writer.write("\nCondition:      " + item.getCondition());
                writer.write("\nSeller:         " + item.getSeller());
                writer.write("\n-------------------------------------");
                writer.write("\nThank you for using EquipWise!");
                writer.write("\n-------------------------------------");
                writer.write("\n");
                
                writer.close();
                receiptCount ++;    //increasing count after writingto receipt
            
            } catch(IOException e) {
                e.printStackTrace();
            } //end try/catch
            
            return fileName;
        
        } //end generateReceipt()
    
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JToggleButton btnOrder;
    private javax.swing.JLabel lblCondition;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblSeller;
    // End of variables declaration//GEN-END:variables
}
